### PR TITLE
New Package Name

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Comment by redreceipt** [comment]
I think this should cover our bases

**Review by vinnyjth — CHANGES_REQUESTED** [review]
This may be considered overkill, but we should probably handle both the old naming and the new naming. That way if you update to a version pre-1.6 (like you are updating incrementally) you won't run into trouble. 

I don't think it is a huge additional code burden to support both, but let me know what you think.

**Comment by redreceipt** [comment]
yea I agree

**Review by vinnyjth — APPROVED** [review]

**Comment by vinnyjth** [comment]
Thanks :D Hopefully you had fun with your first poke around the update tool codebase ;)

**Pull request merged**
